name: "dev stage test-lint"

on:
    push:
        branches: [dev]
    workflow_dispatch:

jobs:
    dev_ci:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        env:
            GH_TOKEN: ${{github.token}}
        steps:
            -   uses: actions/checkout@v5
                with: 
                    fetch-depth: 0
            
            -   name: use node
                uses: actions/setup-node@v5
                with: 
                    node-version: "20.11"

            -   name: Cache Node modules
                uses: actions/cache@v4
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-
            
            -   name: install dependencies
                run: npm ci

            -   name: List files in workspace
                run: ls -R

            -   name: run tests
                run: npm run test            
            
            -   name: run lint
                run: npm run lint
   
            -   name: Create pull request
                run: |
                    export PR_BRANCH=$(git branch --show-current)
                    export DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
                    gh pr list --head "$PR_BRANCH" --base "$DEFAULT_BRANCH" --json number --jq '.[0].number' > pr_number.txt
                    if [ -s pr_number.txt ]; then
                        echo "PR already exists."
                    else
                        gh pr create --title "Automated PR from Dev Stage" --body "${{ github.repository }}" --base "$DEFAULT_BRANCH" --head "$PR_BRANCH"
                    fi